name: Compilar Gamemode SA-MP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Baixar Dependências (Includes)
      run: |
        wget https://github.com/pawn-lang/samp-stdlib/archive/refs/heads/master.tar.gz -O samp-stdlib.tar.gz
        tar -xzf samp-stdlib.tar.gz
        wget https://github.com/pawn-lang/pawn/archive/refs/heads/master.tar.gz -O pawn-master.tar.gz
        tar -xzf pawn-master.tar.gz

    - name: Instalar o compilador Pawn
      run: |
        curl -L -o pawnc.tar.gz https://github.com/pawn-lang/compiler/releases/download/v3.10.10/pawnc-3.10.10-linux.tar.gz
        tar -xzf pawnc.tar.gz
        sudo cp pawnc-3.10.10-linux/bin/pawncc /usr/local/bin/
        sudo cp pawnc-3.10.10-linux/lib/libpawnc.so /usr/local/lib/
        sudo ldconfig
        sudo chmod +x /usr/local/bin/pawncc

    - name: Compilar o gamemode
      run: |
        pawncc nfs.pwn -onfs.amx -i./samp-stdlib-master -i./pawn-master/include

    - name: Fazer upload do arquivo compilado
      uses: actions/upload-artifact@v4
      with:
        name: gamemode-amx
        path: nfs.amx
